### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.nearby.connection.ConnectionsClient, but class was expected (declaration of 'com.google.android.gms.nearby.connection.ConnectionsClient' 

### ISSUE THREAD

**Issue by Jules369-ZM** [VNAPNIC/flutter_nearby_connections#23]
FATAL EXCEPTION: main
E/AndroidRuntime(10222): Process: com.example.near_by_api_ex, PID: 10222
E/AndroidRuntime(10222): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.nearby.connection.ConnectionsClient, but class was expected (declaration of 'com.google.android.gms.nearby.connection.ConnectionsClient' appears in /data/app/com.example.near_by_api_ex-SQmqvcjOXV3emcH2l_ILUw==/base.apk)
E/AndroidRuntime(10222): 	at com.nankai.flutter_nearby_connections.NearbyService.stopDiscovery(NearbyService.kt:72)
E/AndroidRuntime(10222): 	at com.nankai.flutter_nearby_connections.FlutterNearbyConnectionsPlugin.onMethodCall(FlutterNearbyConnectionsPlugin.kt:111)
E/AndroidRuntime(10222): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(10222): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(10222): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(10222): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(10222): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(10222): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(10222): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10222): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(10222): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (10222): Sending signal. PID: 10222 SIG: 9

please i need help

**Comment by thirstyde** [comment]
Please give me a solution
